Models/Budget/Depense.cs
using System;
using Admins.Models.Budget.List;
using Admins.Traitements.Generic.Attributes;
using Admins.Traitements.Generic.Base;
using Admins.Traitements.Generic.Util;

namespace Admins.Models.Budget
{
    [ListEditable]
    [ListDeletable(TypeBaseModel = typeof(Depenses))]
    [Forms("Nouveau dépense", "Modification d'une depense", SaveAndCreateAnOther = true)]
    [Lists("Liste des dépense", typeof(Depenses))]
    public class Depense : BaseModel
    {
        private string _idTypeDepense;
        private string _description;
        private decimal _valeur;
        private DateTime _dateAjout = DateTime.Now;
        
        [Champ(nameof(TypeDepense.Designation), "Depense", typeof(TypeDepense), SelectDB = true, Class = Use.ClFormSelect2)]
        public string IdTypeDepense
        {
            get { return _idTypeDepense; }
            set
            {
                if(string.IsNullOrEmpty(value))
                    throw new Exception("Mentionné le type de votre depense");
                _idTypeDepense = value;
            }
        }

        [Champ(Label = nameof(Description))]
        public string Description
        {
            get { return _description; }
            set { _description = value; }
        }

        [Champ(Label = nameof(Valeur), Type = Champ.Numeric)]
        [NumberFormat]
        public decimal Valeur
        {
            get { return _valeur; }
            set
            {
                if(value <= 0)
                    throw new Exception("Valeur du dépense negatif ou zéro invalide");
                _valeur = value;
            }
        }

        [Champ(Label = "Date", Type = Champ.Datetime)]
        [DateTimeFormat("d")]
        public DateTime DateAjout
        {
            get { return _dateAjout; }
            set { _dateAjout = value; }
        }
    }
}

Models/Budget/List/Depenses.cs
using System;
using Admins.Traitements.Generic.Attributes;
using Admins.Traitements.Generic.Base;

namespace Admins.Models.Budget.List
{
    [PreviewDetails(TypeBaseModel = typeof(Depenses))]
    [ListDeletable(TypeBaseModel = typeof(Depense))]
    [ListEditable(TypeBaseModel = typeof(Depense))]
    [Lists("Liste des Depenses")]
    [Forms(typeof(Depense))]
    public class Depenses : BaseModel
    {
        private string _idTypeDepense;
        private string _designation;
        private string _description;
        private decimal _valeurMax;
        private decimal _valeurMin;
        private decimal _valeur;
        private DateTime _dateAjout;
        private decimal _parJour;

        [Hide]
        public string IdTypeDepense
        {
            get { return _idTypeDepense; }
            set { _idTypeDepense = value; }
        }

        [Champ]
        public string Designation
        {
            get { return _designation; }
            set { _designation = value; }
        }

        [Champ]
        public string Description
        {
            get { return _description; }
            set { _description = value; }
        }

        [Champ(Label = "Valeurs", Type = "numeric")]
        [NumberFormat]
        public decimal Valeur
        {
            get { return _valeur; }
            set { _valeur = value; }
        }

        [Champ(Label = "Date", Type = "date")]
        [DateTimeFormat("D")]
        public DateTime DateAjout
        {
            get { return _dateAjout; }
            set { _dateAjout = value; }
        }

        [NumberFormat]
        [Champ(Label = "Par jour", Type = "numeric")]
        public decimal ParJour
        {
            get { return _parJour; }
            set { _parJour = value; }
        }

        [NumberFormat]
        [Champ(Label = "Min", Type = "numeric")]
        public decimal ValeurMin
        {
            get { return _valeurMin; }
            set { _valeurMin = value; }
        }
        
        [NumberFormat]
        [Champ(Label = "Max", Type = "numeric")]
        public decimal ValeurMax
        {
            get { return _valeurMax; }
            set { _valeurMax = value; }
        }
    }
}

Models/Budget/Model/StateChartViewModel.cs
using System;

namespace Admins.Models.Budget.Model
{
    public class StateChartViewModel
    {
        public DateTime Date { get; set; }

        public TypeDepense Global { get; set; } = new TypeDepense
        {
            Id = "_All",
            Designation = "Global"
        };

        public TypeDepense[] TypeDepenses { get; set; }
    }
}

Models/Budget/Model/StateTableViewModel.cs
using System;
using Admins.Traitements.Models;

namespace Admins.Models.Budget.Model
{
    public class StateTableViewModel : ListViewModel
    {
        public DateTime Date { get; set; }
    }
}

Models/Budget/PorteFeuille.cs
using Admins.Traitements.Generic.Attributes;
using Admins.Traitements.Generic.Base;

namespace Admins.Models.Budget
{
    [Forms("Ajouter au porte feuille")]
    [TableInfo("PORTE_FEUILLE", "PORTE_FEUILLE_ID","")]
    public class PorteFeuille : BaseModel
    {
        public decimal Valeur { get; set; }
    }
}

Models/Budget/PorteFeuilleBudget.cs
namespace Admins.Models.Budget
{
    public class PorteFeuilleBudget
    {
        private decimal _hebdomadaire;
        private decimal _mensuel;
        private decimal _porteFeuille;

        public decimal Hebdomadaire
        {
            get { return _hebdomadaire; }
            set { _hebdomadaire = value; }
        }

        public decimal Mensuel
        {
            get { return _mensuel; }
            set { _mensuel = value; }
        }

        public decimal PorteFeuille
        {
            get { return _porteFeuille; }
            set { _porteFeuille = value; }
        }
    }
}

Models/Budget/State/StateAnnuel.cs
using Admins.Traitements.Generic.Attributes;
using Admins.Traitements.Generic.Attributes.Chart;
using Admins.Traitements.Generic.Base;

namespace Admins.Models.Budget.State
{
    [ChartType(Title = "Depense - Ariary")]
    [Lists("Depense mensuel")]
    public class StateAnnuel : BaseChart
    {
        [Champ]
        public string Designation { get; set; }

        [ChartInfo]
        [NumberFormat]
        public decimal Janvier { get; set; }

        [ChartInfo]
        [NumberFormat]
        public decimal Fevrier { get; set; }

        [ChartInfo]
        [NumberFormat]
        public decimal Mars { get; set; }

        [ChartInfo]
        [NumberFormat]
        public decimal Avril { get; set; }

        [ChartInfo]
        [NumberFormat]
        public decimal Mai { get; set; }

        [ChartInfo]
        [NumberFormat]
        public decimal Juin { get; set; }

        [ChartInfo]
        [NumberFormat]
        public decimal Juillet { get; set; }

        [ChartInfo]
        [NumberFormat]
        public decimal Aout { get; set; }

        [ChartInfo]
        [NumberFormat]
        public decimal Septembre { get; set; }

        [ChartInfo]
        [NumberFormat]
        public decimal Octobre { get; set; }

        [ChartInfo]
        [NumberFormat]
        public decimal Novembre { get; set; }

        [ChartInfo]
        [NumberFormat]
        public decimal Decembre { get; set; }

        [NotColumn]
        [NumberFormat]
        [Champ(Label = "Total")]
        public decimal Total { get; set; }

        public override decimal TotalDefault()
        {
            return Janvier + Fevrier + Mars + Avril + Mai + Juin + Juillet + Aout + Septembre + Octobre + Novembre + Decembre;
        }
    }
}

Models/Budget/State/StateHebdomadaire.cs
using Admins.Traitements.Generic.Attributes;
using Admins.Traitements.Generic.Attributes.Chart;
using Admins.Traitements.Generic.Base;

namespace Admins.Models.Budget.State
{
    [ChartType(Title = "Depense - Ariary")]
    [Lists("Depense hebdomadaire")]
    public class StateHebdomadaire : BaseChart
    {
        [Champ]
        public string Designation { get; set; }

        [ChartInfo]
        [NumberFormat]
        public decimal Dimanche { get; set; }

        [ChartInfo]
        [NumberFormat]
        public decimal Lundi { get; set; }

        [ChartInfo]
        [NumberFormat]
        public decimal Mardi { get; set; }

        [ChartInfo]
        [NumberFormat]
        public decimal Mercredi { get; set; }

        [ChartInfo]
        [NumberFormat]
        public decimal Jeudi { get; set; }

        [ChartInfo]
        [NumberFormat]
        public decimal Vendredi { get; set; }

        [ChartInfo]
        [NumberFormat]
        public decimal Samedi { get; set; }

        [NotColumn]
        [NumberFormat]
        [Champ(Label = "Total/Semaine")]
        public decimal Total { get; set; }

        [NotColumn]
        [NumberFormat]
        [Champ(Label = "Max/Semaine")]
        public decimal Maximum { get; set; }


        public override decimal TotalDefault()
        {
            return Dimanche + Lundi + Mardi + Mercredi + Jeudi + Vendredi + Samedi;
        }
    }
}

Models/Budget/State/StateMensuel.cs
using System;
using Admins.Traitements.Generic.Base;

namespace Admins.Models.Budget.State
{
    public class StateMensuel : BaseChart
    {
        public decimal Semaine1 { get; set; }

        public decimal Semaine2 { get; set; }

        public decimal Semaine3 { get; set; }

        public decimal Semaine4 { get; set; }

        public override decimal TotalDefault()
        {
            throw new NotImplementedException();
        }
    }
}

Models/Budget/TypeDepense.cs
using System;
using Admins.Traitements.Generic.Attributes;
using Admins.Traitements.Generic.Base;

namespace Admins.Models.Budget
{
    [ListEditable]
    [Lists("Differente type de dépense")]
    [Forms("Nouveau Type de dépense", "Modification d'un Type de dépense")]
    public class TypeDepense : BaseModel
    {
        private string _designation;
        private decimal _valeurMin;
        private decimal _valeurMax;
        private decimal _parJour;
        private decimal _parSemaine;
        private decimal _parMois;

        [Champ(Label = "Désignation")]
        public string Designation
        {
            get { return _designation; }
            set { _designation = value; }
        }

        [Champ(Label = "Par jour", Type = Champ.Numeric)]
        [NumberFormat]
        public decimal ParJour
        {
            get { return _parJour; }
            set
            {
                if(value < 0)
                    throw new Exception("Valeur `Par jour` negaitve à zero invalide.");
                _parJour = value;
            }
        }

        [Champ(Label = "Par semaine", Type = Champ.Numeric)]
        [NumberFormat]
        public decimal ParSemaine
        {
            get { return _parSemaine; }
            set
            {
                if(value < 0)
                    throw new Exception("Valeur `Par semaine negaitve à zero invalide.");
                _parSemaine = value;
            }
        }

        [Champ(Label = "Par mois", Type = Champ.Numeric)]
        [NumberFormat]
        public decimal ParMois
        {
            get { return _parMois; }
            set
            {
                if(value < 0)
                    throw new Exception("Valeur `Par mois` negaitve à zero invalide.");
                _parMois = value;
            }
        }

        [Champ(Label = "Valeur min.", Type = Champ.Numeric)]
        [NumberFormat]
        public decimal ValeurMin
        {
            get
            {
                return _valeurMin;
            }
            set
            {
                if(value < 0)
                    throw new Exception("Valeur min negaitve à zero invalide.");
                _valeurMin = value;
            }
        }

        [Champ(Label = "Valeur max.", Type = Champ.Numeric)]
        [NumberFormat]
        public decimal ValeurMax
        {
            get { return _valeurMax; }
            set
            {
                if(value < 0)
                    throw new Exception("Valeur max negaitve à zero invalide.");
                if(value <= _valeurMin)
                    throw new Exception("Valeur max doit superieur à la valeur min.");
                _valeurMax = value;
            }
        }
    }
}

Controllers/BudgetController.cs
using System;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Admins.Models.Budget;
using Admins.Models.Budget.Model;
using Admins.Models.Budget.State;
using Admins.Services.Budget;
using Admins.Traitements.Action;
using Admins.Traitements.Services.Repository;

namespace Admins.Controllers
{
    public class BudgetController : BaseController
    {
        private readonly IStatistiqueBudgetService _service;
        private readonly IDataBaseModel _model;

        public BudgetController(IStatistiqueBudgetService service, IDataBaseModel model)
        {
            _service = service;
            _model = model;
        }

        public ActionResult StateChart(DateTime? date)
        {
            return ViewProtected(View(new StateChartViewModel
            {
                Date = date ?? DateTime.Now,
                TypeDepenses = _model.Find(new TypeDepense()).Cast<TypeDepense>().ToArray()
            }));
        }

        public ActionResult StateTable(DateTime? date)
        {
            try
            {
                var state = new StateHebdomadaire();
                return ViewProtected(View(new StateTableViewModel
                {
                    BoxTitle = new HtmlString(state.ListBoxTitle()),
                    Modeles = _service.Hebdomadaire(date ?? DateTime.Now),
                    Date = date ?? DateTime.Now
                }));
            }
            catch (Exception e)
            {
                return ViewError(e.GetBaseException().Message);
            }
        }

        public ActionResult StateTableAnnuel(DateTime? date)
        {
            try
            {
                var state = new StateAnnuel();
                return ViewProtected(View(new StateTableViewModel
                {
                    BoxTitle = new HtmlString(state.ListBoxTitle()),
                    Modeles = _service.Annuel(date ?? DateTime.Now),
                    Date = date ?? DateTime.Now
                }));
            }
            catch (Exception e)
            {
                return ViewError(e.GetBaseException().Message);
            }
        }

        public JsonResult JsonState(string typeId, DateTime? date)
        {
            var state = _service.Get(typeId, date ?? DateTime.Now);
            return Json(state.DataChart("C"), JsonRequestBehavior.AllowGet);
        }

        public JsonResult JsonGlobalState(DateTime? date)
        {
            var state = _service.GetGlobal(date ?? DateTime.Now);
            return Json(state.DataChart("C"), JsonRequestBehavior.AllowGet);
        }
    }
}

Views/Budget/StateChart.cshtml
@using Admins.Traitements.Generic.Html
@using Admins.Traitements.Generic.Util
@model Admins.Models.Budget.Model.StateChartViewModel
@{
    var types = Model.TypeDepenses;
    var button = Boutton.Build("submit", "Chercher", "btn btn-default");
    var daty = Model.Date.ToString("yyyy-MM-dd");
    var semaine = new Semaine(Convert.ToDateTime(daty));
}
<link rel="stylesheet" href="/Content/Plugins/iChart/Chart.min.css">
<div class="row">
    <div class="box">
        <div class="col-md-4">
            <form action="@Url.Action("StateChart", "Budget")" method="get">
                <div class="box-body">
                    @Html.Raw(Input.BuildWithBtn("date", "date", daty, button, "Semaine De :"))
                </div>
            </form>
        </div>
        <div style="text-align: center;" class="col-md-8">
            <h5>@semaine.Dimanche.ToString("D") au @semaine.Samedi.ToString("D")</h5>
        </div>
    </div>
</div>
<div class="row">
    <section class="col-lg-12 connectedSortable">
        <div class="nav-tabs-custom">
            <ul class="nav nav-tabs pull-right">
                <li class="active">
                    <a href="#@Model.Global.Id" data-toggle="tab">@Model.Global.Designation</a>
                </li>
                @foreach (var type in types)
                {
                    <li>
                        <a href="#@type.Id" data-toggle="tab">@type.Designation</a>
                    </li>
                }
                <li class="pull-left header"><i class="fa fa-bar-chart"></i> :</li>
            </ul>
            <div class="tab-content">
                <div class="chart tab-pane active" id="@Model.Global.Id" style="min-height: 560px; position: relative;">
                    <canvas id="@Model.Global.IdChart(Model.Global.Id)"></canvas>
                    <hr/>
                    <div id="TOTAL_@Model.Global.IdChart(Model.Global.Id)" class="text-center">
                        @*Total Data*@
                    </div>
                </div>
                @foreach (var type in types)
                {
                    <div class="chart tab-pane" id="@type.Id" style="height: 560px; position: relative;">
                        <canvas id="@type.IdChart(type.Id)"></canvas>
                        <hr/>
                        <div id="TOTAL_@type.IdChart(type.Id)" class="text-center">
                            @*Total Data*@
                        </div>
                    </div>
                }
            </div>
        </div>
    </section>
</div>


<script src="/Content/Plugins/iChart/Chart.min.js"></script>
<script>
    function SetChart(chartId, typeId) {
        $.ajax({
            url: '@Url.Action("JsonState", "Budget")',
            data:"typeId="+typeId+"&date=@daty",
            success:function(result) {
                $("#TOTAL_" + chartId).html("<strong>Total : "+result.data.total+"</strong>");
                let myChart = new Chart($('#'+chartId), result);
            }
        });
    }
    
    function SetGlobalChart(chartId) {
        $.ajax({
            url: '@Url.Action("JsonGlobalState", "Budget")',
            data:"date=@daty",
            success:function(result) {
                $("#TOTAL_" + chartId).html("<strong>Total : "+result.data.total+"</strong>");
                let myChart = new Chart($('#'+chartId), result);
            }
        }); 
    }
    
    $(document).ready(function() {
    @foreach (var type in Model.TypeDepenses)
    {
        <text>SetChart('@type.IdChart(type.Id)', '@type.Id');</text>
    }
        SetGlobalChart('@Model.Global.IdChart(Model.Global.Id)');
    });
</script>

Views/Budget/StateTable.cshtml
@using Admins.Traitements.Generic.Html
@using Admins.Traitements.Generic.Util
@model Admins.Models.Budget.Model.StateTableViewModel
@{
    var button = Boutton.Build("submit", "Chercher", "btn btn-default");
    var daty = Model.Date.ToString("yyyy-MM-dd");
    var semaine = new Semaine(Convert.ToDateTime(daty));
}

<div class="row">
    <div class="box">
        <div class="col-lg-4">
            <form action="@Url.Action("StateTable", "Budget")" method="get">
                <div class="box-body">
                    @Html.Raw(Input.BuildWithBtn("date", "date", daty, button, "Semaine de"))
                </div>
            </form>
        </div>
        <div style="text-align: center;" class="col-lg-8">
            <h5>@semaine.Dimanche.ToString("D") au @semaine.Samedi.ToString("D")</h5>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-md-12">
        <div class="box">
            <div class="box-header with-border">
                <h3 class="box-title">@Model.BoxTitle</h3>
            </div>
            <div class="box-body table-overflow-x table-responsive no-padding">
                @Table.GetTable(Model.Modeles, Model.IsChoix)
            </div>
            @*
                <div class="box-footer table-condensed clearfix">
                </div>
            *@
        </div>
    </div>
</div>

Views/Budget/StateTableAnnuel.cshtml
@using Admins.Traitements.Generic.Html
@using Admins.Traitements.Generic.Util
@model Admins.Models.Budget.Model.StateTableViewModel
@{
    var button = Boutton.Build("submit", "Chercher", "btn btn-default");
    var daty = Model.Date.ToString("yyyy-MM-dd");
    var semaine = new Semaine(Convert.ToDateTime(daty));
}

<div class="row">
    <div class="box">
        <div class="col-lg-4">
            <form action="@Url.Action("StateTableAnnuel", "Budget")" method="get">
                <div class="box-body">
                    @Html.Raw(Input.BuildWithBtn("date", "date", daty, button, "Ann&eacute;e"))
                </div>
            </form>
        </div>
        <div style="text-align: center;" class="col-lg-8">
            <h2>Ann&eacute;e: @DateTime.Now.Year</h2>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-md-12">
        <div class="box">
            <div class="box-header with-border">
                <h3 class="box-title">@Model.BoxTitle</h3>
            </div>
            <div class="box-body table-overflow-x table-responsive no-padding">
                @Table.GetTable(Model.Modeles, Model.IsChoix)
            </div>
            @*
                <div class="box-footer table-condensed clearfix">
                </div>
            *@
        </div>
    </div>
</div>